Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TennisAustraliaAssignment.Data;
using TennisAustraliaAssignment.Models;

namespace TennisAustraliaAssignment.Controllers
{
    public class MatchesController : Controller
    {
        private readonly TennisContext _context;

        public MatchesController(TennisContext context)
        {
            _context = context;
        }

        // GET: Matches
        public async Task<IActionResult> Index()
        {
            var tennisContext = _context.Matches.Include(m => m.Registration).Include(m => m.Registration.Player).Include(m => m.TournamentBracket).Include(m => m.Registration);
            return View(await tennisContext.ToListAsync());
        }

        // GET: Matches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = await _context.Matches
                .Include(m => m.Registration)
                .Include(m => m.Registration.Player)
                .Include(m => m.TournamentBracket)
                .FirstOrDefaultAsync(m => m.MatchID == id);
            if (match == null)
            {
                return NotFound();
            }

            return View(match);
        }

        // GET: Matches/Create
        public IActionResult Create()
        {
            ViewData["TournamentBracketID"] = new SelectList(_context.TournamentBrackets, "TournamentBracketID", "TournamentBracketID");
            ViewData["RegistrationID"] = new SelectList(_context.RegistrationDetails, "RegistrationID", "RegistrationID");
            ViewData["RegistrationID"] = new SelectList(_context.RegistrationDetails, "RegistrationID", "RegistrationID");
            return View();
        }

        // POST: Matches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MatchID,Round,TournamentBracketID,FirstRegistrationID,SecondRegistrationID,RegistrationID")] Match match)
        {
            if (ModelState.IsValid)
            {
                _context.Add(match);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TournamentBracketID"] = new SelectList(_context.TournamentBrackets, "TournamentBracketID", "TournamentBracketID", match.TournamentBracketID);
            ViewData["RegistrationID"] = new SelectList(_context.registrations, "RegistrationID", "RegistrationID", match.FirstRegistrationID);
            ViewData["RegistrationID"] = new SelectList(_context.registrations, "RegistrationID", "RegistrationID", match.SecondRegistrationID);
            return View(match);
        }

        // GET: Matches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = await _context.Matches.FindAsync(id);
            if (match == null)
            {
                return NotFound();
            }
            ViewData["TournamentBracketID"] = new SelectList(_context.TournamentBrackets, "TournamentBracketID", "TournamentBracketID", match.TournamentBracketID);
            ViewData["RegistrationID"] = new SelectList(_context.registrations, "RegistrationID", "RegistrationID", match.FirstRegistrationID);
            ViewData["RegistrationID"] = new SelectList(_context.registrations, "RegistrationID", "RegistrationID", match.SecondRegistrationID);
            return View(match);
        }

        // POST: Matches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MatchID,Round,TournamentBracketID,FirstRegistrationID,SecondRegistrationID,RegistrationID")] Match match)
        {
            if (id != match.MatchID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(match);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MatchExists(match.MatchID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TournamentBracketID"] = new SelectList(_context.TournamentBrackets, "TournamentBracketID", "TournamentBracketID", match.TournamentBracketID);
            ViewData["RegistrationID"] = new SelectList(_context.registrations, "RegistrationID", "RegistrationID", match.FirstRegistrationID);
            ViewData["RegistrationID"] = new SelectList(_context.registrations, "RegistrationID", "RegistrationID", match.SecondRegistrationID);
            return View(match);
        }

        // GET: Matches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = await _context.Matches
                .Include(m => m.Registration)
                .Include(m => m.Registration.Player)
                .Include(m => m.TournamentBracket)
                .FirstOrDefaultAsync(m => m.MatchID == id);
            if (match == null)
            {
                return NotFound();
            }

            return View(match);
        }

        // POST: Matches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var match = await _context.Matches.FindAsync(id);
            _context.Matches.Remove(match);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MatchExists(int id)
        {
            return _context.Matches.Any(e => e.MatchID == id);
        }
    }
}

Controllers/VenuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TennisAustraliaAssignment.Data;
using TennisAustraliaAssignment.Models;

namespace TennisAustraliaAssignment.Controllers
{
    public class VenuesController : Controller
    {
        private readonly TennisContext _context;

        public VenuesController(TennisContext context)
        {
            _context = context;
        }

        // GET: Venues
        public async Task<IActionResult> Index()
        {
            var tennisContext = _context.Venue.Include(v => v.Surface);
            return View(await tennisContext.ToListAsync());
        }

        // GET: Venues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue
                .Include(v => v.Surface)
                .FirstOrDefaultAsync(m => m.VenueID == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }

        // GET: Venues/Create
        public IActionResult Create()
        {
            ViewData["SurfaceID"] = new SelectList(_context.Surface, "SurfaceID", "SurfaceName");
            return View();
        }

        // POST: Venues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VenueID,VenueName,Street,City,State,SurfaceID")] Venue venue)
        {
            if (ModelState.IsValid)
            {
                _context.Add(venue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SurfaceID"] = new SelectList(_context.Surface, "SurfaceID", "SurfaceName", venue.SurfaceID);
            return View(venue);
        }

        // GET: Venues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue.FindAsync(id);
            if (venue == null)
            {
                return NotFound();
            }
            ViewData["SurfaceID"] = new SelectList(_context.Surface, "SurfaceID", "SurfaceName", venue.SurfaceID);
            return View(venue);
        }

        // POST: Venues/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VenueID,VenueName,Street,City,State,SurfaceID")] Venue venue)
        {
            if (id != venue.VenueID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VenueExists(venue.VenueID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SurfaceID"] = new SelectList(_context.Surface, "SurfaceID", "SurfaceName", venue.SurfaceID);
            return View(venue);
        }

        // GET: Venues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue
                .Include(v => v.Surface)
                .FirstOrDefaultAsync(m => m.VenueID == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }

        // POST: Venues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venue = await _context.Venue.FindAsync(id);
            _context.Venue.Remove(venue);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VenueExists(int id)
        {
            return _context.Venue.Any(e => e.VenueID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tennis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <!-- Nav Container-->
        <nav class="navbar">
            <!-- Image with link-->
            <a href="https://www.tennis.com.au/tournaments"><img src="~/TennisLogo.png" alt="Tennis Logo" width="100" height="100"></a>
            <div class="container">
                <ul>
                    <!-- Home-->
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li>
                        <!-- Drop down selection of choices -->
                        <div class="dropdown">
                            <button class="dropbtn">Players and Organiser Details</button>
                            <div class="dropdown-content">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">Players</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organisers" asp-action="Index">Organisers</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registrations" asp-action="Index">Registrations</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="RegistrationDetails" asp-action="Index">Registration Details</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <!-- Drop down selection of choices -->
                        <div class="dropdown">
                            <button class="dropbtn">Tournaments and Games</button>
                            <div class="dropdown-content">
                                <a asp-area="" asp-controller="AgeBrackets" asp-action="Index">Age Brackets</a>
                                <a asp-area="" asp-controller="TournamentTypes" asp-action="Index">Tournament Types</a>
                                <a asp-area="" asp-controller="LeagueRatings" asp-action="Index">League Ratings</a>
                                <a asp-area="" asp-controller="Surfaces" asp-action="Index">Surfaces</a>
                                <a asp-area="" asp-controller="Venues" asp-action="Index">Venues</a>
                                <a asp-area="" asp-controller="Tournaments" asp-action="Index">Tournaments</a>
                                <a asp-area="" asp-controller="TournamentBrackets" asp-action="Index">Tournament Brackets</a>
                                <a asp-area="" asp-controller="Matches" asp-action="Index">Matches</a>
                                <a asp-area="" asp-controller="SetResults" asp-action="Index">Set results</a>
                                <a asp-area="" asp-controller="FinaleResults" asp-action="Index">Finale results</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TennisAustraliaAssignment
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>